### ISSUE TITLE
UniformIntervalGenerator implementation is Buggy

### ISSUE THREAD

**Issue by jamesmaa** [pinterest/bender#15]
```golang
// UniformIntervalGenerator creates and IntervalGenerator that outputs 1/rate every time it is
// called. Boring, right?
func UniformIntervalGenerator(rate float64) IntervalGenerator {
	irate := int64(rate / float64(time.Second))
	return func(_ int64) int64 {
		return irate
	}
}
```
This implementation is buggy because if I pass in `float64(time.Second)` for rate, then `irate = 1`, and that value is passed into `LoadTestThroughput` as a Duration value, which means the wait time will be 1 nanosecond. If I pass in `1.0` with the intention of 1.0 QPS, then the resulting wait time will be 0 nanoseconds.

Looks like `irate` should be `int64(float64(time.Second) / rate)` instead of the other way around. The comments suggests that this should be the case.

Changing to the proposed fix will also help create a consistent API with `ExponentialIntervalGenerator` (i.e. passing in the QPS value).

This is a Golang playground that demonstrates my understanding. I substituted the math from the functions and used the same QPS rate for both.
https://play.golang.org/p/jKXTYHWSC2

I can make a pull request if this a legitimate bug.

**Comment by cgordon** [comment]
Yes, this is a bug, thank you for tracking it down. If you can submit a pull request, I can approve it!

**Comment by jamesmaa** [comment]
Fixed: https://github.com/pinterest/bender/pull/16
