### ISSUE TITLE
not enough arguments in thrift/thrift.go

### ISSUE THREAD

**Issue by advancedwebdeveloper** [pinterest/bender#40]
Hi.
I am experiencing some issues, while building your project.

> ~/bender/thrift$ go build
> thrift.go:24:2: cannot find package "git.apache.org/thrift.git/lib/go/thrift" in any of:
> 	/home/oceanfish81/gollvm_dist/src/git.apache.org/thrift.git/lib/go/thrift (from $GOROOT)
> 	/home/oceanfish81/go/src/git.apache.org/thrift.git/lib/go/thrift (from $GOPATH)
> 
> ~/bender/thrift$ go get -u git.apache.org/thrift.git/lib/go/thrift
> $ go build
> # _/home/oceanfish81/bender/thrift
> ./thrift.go:35:25: error: not enough arguments
> ./thrift.go:55:38: error: not enough arguments
> ./thrift.go:60:16: error: argument 1 has incompatible type (missing method 'Deadline')
> ./thrift.go:60:10: error: not enough arguments

> ~/bender$ git pull
> Already up to date.
> 

I am using
> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64
.

Here is my environment:
> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build167274628=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
>

**Comment by earlgreyz** [comment]
https://github.com/pinterest/bender/pull/42

**Comment by earlgreyz** [comment]
This can be closed as #42 got merged. @jparise
