### ISSUE TITLE
Issues with running go install 

### ISSUE THREAD

**Issue by davlucal** [pinterest/bender#44]
![Screen Shot 2021-06-02 at 2 54 21 AM](https://user-images.githubusercontent.com/59355541/120445053-d9dd7700-c34d-11eb-90fe-2df0250ceec4.png)

Also, when running " thrift --out src/hellothrift --gen go:package_prefix=src/hellothrift src/hellothrift/hello.thrift" , i do not get the exact 3 files in the hello directory. 

![Screen Shot 2021-06-02 at 2 55 05 AM](https://user-images.githubusercontent.com/59355541/120445720-84ee3080-c34e-11eb-9479-53e342dc0aba.png)

Any ideas?

**Comment by davlucal** [comment]
I debugged all the error messages when running both the client and server's main.go. Here are the code changes.

**Comment by davlucal** [comment]
For client/main.go:

```
package main

import (
	"fmt"
	"hellothrift/hello"
	"context"
	"github.com/apache/thrift/lib/go/thrift"
)

func RunClient(transportFactory thrift.TTransportFactory, protocolFactory thrift.TProtocolFactory, addr string) error {
	socket, err := thrift.NewTSocket(addr)
	if err != nil {
		return err
	}

	transport, err := transportFactory.GetTransport(socket)
	defer transport.Close()
	if err := transport.Open(); err != nil {
		return err
	}

	client := hello.NewHelloClientFactory(transport, protocolFactory)
	request := hello.NewHelloRequest()
	temp := "hello world"
	request.Message = &temp
 	response, err := client.Hello(context.Background(), request)
	if err != nil {
		return err
	}
	fmt.Println(*response.Message)

	return nil
}

func main() {
	transportFactory := thrift.NewTFramedTransportFactory(thrift.NewTTransportFactory())
	protocolFactory := thrift.NewTBinaryProtocolFactoryDefault()
	addr := "localhost:3636"
	err := RunClient(transportFactory, protocolFactory, addr)
	if err != nil {
	    panic(err)
	}
}

```

**Comment by davlucal** [comment]
For server/main.go

```
package main

import (
	"context"
	"hellothrift/hello"
	"fmt"
	"time"
	"github.com/apache/thrift/lib/go/thrift"
)


type HelloHandler struct {

}

func (*HelloHandler) Hello(ctx context.Context, request *hello.HelloRequest) (*hello.HelloResponse, error) {
	resp := hello.NewHelloResponse()
	resp.Message = request.Message
	fmt.Printf("%d - %s\n", time.Now().UnixNano(), request.Message)
	return resp, nil
}

func NewHelloHandler() hello.Hello {
	return new(HelloHandler)
}

func RunServer(transportFactory thrift.TTransportFactory, protocolFactory thrift.TProtocolFactory, addr string) error {
	transport, err := thrift.NewTServerSocket(addr)
	if err != nil {
		return err
	}

	handler := NewHelloHandler()
	processor := hello.NewHelloProcessor(handler)
	server := thrift.NewTSimpleServer4(processor, transport, transportFactory, protocolFactory)

	return server.Serve()
}

func main() {
	transportFactory := thrift.NewTFramedTransportFactory(thrift.NewTTransportFactory())
	protocolFactory := thrift.NewTBinaryProtocolFactoryDefault()
	addr := "localhost:3636"
	RunServer(transportFactory, protocolFactory, addr)
}

```

**Comment by davlucal** [comment]
Output:

![Screen Shot 2021-06-02 at 5 50 01 PM](https://user-images.githubusercontent.com/59355541/120561876-fb307880-c3ca-11eb-90f5-ea55c7b99a8a.png)

There was some issue with one of the functions requiring a pointer to string and not the actual string which is why you see the address being outputted on server side(didn't update this part, only on the client side for the output).

**Comment by davlucal** [comment]
For hellobender/main.go

```
package main

import (
	"github.com/pinterest/bender"
	bthrift "github.com/pinterest/bender/thrift"
	"git.apache.org/thrift.git/lib/go/thrift"
	gthrift "github.com/apache/thrift/lib/go/thrift" 
	"log"
	"os"
	"github.com/pinterest/bender/hist"
	"fmt"
	"time"
	"context"
    "strconv"
	"hellothrift/hello"
)

func SyntheticRequests(n int) chan interface{} {
	c := make(chan interface{}, 100)
	go func() {
		for i := 0; i < n; i++ {
			request := hello.NewHelloRequest()
			temp := "hello " + strconv.Itoa(i)
			request.Message = &temp
			c <- request
		}
		close(c)
	}()
	return c
}

func HelloExecutor(request interface{}, transport thrift.TTransport) (interface{}, error) {
	pFac := gthrift.NewTBinaryProtocolFactoryDefault()
	client := hello.NewHelloClientFactory(transport, pFac)
	return client.Hello(context.Background(), request.(*hello.HelloRequest))
}

func main() {
	intervals := bender.ExponentialIntervalGenerator(10.0)
	requests := SyntheticRequests(10)
	exec := bthrift.NewThriftRequestExec(thrift.NewTFramedTransportFactory(thrift.NewTTransportFactory()), HelloExecutor, 10 * time.Second, "localhost:3636")
	recorder := make(chan interface{}, 128)
	bender.LoadTestThroughput(intervals, requests, exec, recorder)
	l := log.New(os.Stdout, "", log.LstdFlags)
	h := hist.NewHistogram(60000, 1000000)
	bender.Record(recorder, bender.NewLoggingRecorder(l), bender.NewHistogramRecorder(h))
	fmt.Println(h)
}

```

outputs after running twice:

![Screen Shot 2021-06-02 at 8 05 43 PM](https://user-images.githubusercontent.com/59355541/120570512-ef01e680-c3dd-11eb-836b-e250837f47dd.png)
![Screen Shot 2021-06-02 at 8 06 04 PM](https://user-images.githubusercontent.com/59355541/120570536-fa551200-c3dd-11eb-908b-7d425ee96094.png)

**Comment by cgordon** [comment]
@davlucal Hey, thanks for the interest in bender. This library is in dire need of a massive overhaul, but I haven't found the time to do it (particularly because most of the changes would be breaking, and Go is only recently ready for that kind of thing).

If you want to use bender, I highly recommend the more streamlined version available here:

https://github.com/cgordon/bender

Ignore the README for that repo, as it is out of date. The bender.go and intervals.go are significantly streamlined, and perform quite a lot better than the "official" version. For more details, see the comments here:

https://github.com/pinterest/bender/issues/24

Thanks.

**Comment by davlucal** [comment]
Hi @cgordon does the bender thrift release work for go v0.13.0?

**Comment by cgordon** [comment]
@davlucal I am not sure, and have not tried recently, sorry.

**Comment by cgordon** [comment]
Is it possible that you meant Go v1.13?  Version 0.13.0 is a pre-v1 release that is pretty ancient now.

**Comment by davlucal** [comment]
Sorry my bad, what I had meant to say was Thrift version 0.13.0

**Comment by cgordon** [comment]
No worries, that should have been obvious to me :)

I have not run the 0.13 or 0.14 versions of Thrift, so I don't have any experience with them. The code to integrate Thrift with Bender is pretty simple, so it may not take much to do so, if they have changed their APIs.

**Comment by davlucal** [comment]
Gotcha, my issue is that I am using a client that is created from a framework and is not created from thrift's "ClientFactory" function which is required by type in the bthrift NewThriftRequestExec function

**Comment by davlucal** [comment]
Have one other question, should the values for the interval generator and synthetic requests be the same?

**Comment by cgordon** [comment]
The interval generator is used to determine how often requests are sent by
the load tester. The synthetic request channel is used to fetch the next
request to be sent. Unless you are sending numbers as your requests, they
cannot be the same.

**Comment by davlucal** [comment]
Sry, I meant as in the parameters. 
![Screen Shot 2021-06-09 at 12 43 09 AM](https://user-images.githubusercontent.com/59355541/121299926-b8373f00-c8bb-11eb-9273-01c4aa71e40a.png)

My understanding is that the ExponentialIntervalGenerator function takes in the desired QPS(for this, it would be testing for a desired 300 QPS) and the total # of requests sent would be 8000(just an arbitrary large # of requests).

**Comment by cgordon** [comment]
Apologies for the slow reply. The total number of requests sent by the load
tester is controlled by the requests channel (when that channel is closed,
the load tester exits). You are correct about the exponential interval
generator: the parameter is the number of requests per second, on average.
That last bit is important: the exponential generator simulates a "Poisson
process", so on average over a long period of time the request rate will
match the parameter, but for any given second it will be more or less than
that.
